# Generated by Django 5.1.1 on 2024-09-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCBazar', '0003_alter_category_options_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
