# Generated by Django 5.1.1 on 2024-09-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBazar', '0004_remove_product_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
