# Generated by Django 5.1.1 on 2024-09-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCBazar', '0005_product_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/default.png', upload_to='static/images'),
        ),
    ]
